[package]
name = "flappy_clone"
version = "0.1.0"
authors = ["James Moffett <moonsoft@moonsoftstudios.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.1"
